### ISSUE TITLE
Blimp becomes completely unresponsive during lag

### ISSUE THREAD

**Issue by yl-whosit** [APercy/steampunk_blimp#11]
To reproduce:
use `mesecons_debug` mod's command `/create_lag 200000 1` (makes every dtime = 0.2s)

Now the blimp won't respond at all to pressing `sneak` or `jump` and you won't be able to gain altitude or land it.

I've traced it to this code:
https://github.com/APercy/steampunk_blimp/blob/0712b19f79727a1e04850d304f494e2356100ea2/control.lua#L143-L150

which seems to implement "return to neutral" function?
If I understand it correctly, with high enough lag the "correction" just always overshoots the 0 and this causes any player input to become completely canceled.

**Comment by APercy** [comment]
fixed today! Thank you!
