### ISSUE TITLE
Bucket duplication when loading the blimp with water.

### ISSUE THREAD

**Issue by LissoBone** [APercy/steampunk_blimp#2]
Greetings.

I have noticed that when a player loads the blimp with water from a bucket, an extra empty bucket appears in the inventory. This isn't a great issue, but I would like it to be solved (and I did solve it with this one simple trick discovered by a mom).

Solution: remove or comment out line 78 in the file fuel_management.lua in order to fix this behavior.
I couldn't push the changes to this repository on my own for some reason, so I simply opened an issue here.

I hope you'll find this helpful (if the bucket duplication isn't an intended feature).

![image](https://user-images.githubusercontent.com/62686420/195642950-c5ad2590-52e4-4c47-9d8c-66a3b111d9fb.png)

**Comment by APercy** [comment]
right, I'll check it when I'm at home tonight! thank you!

**Comment by APercy** [comment]
Fixed! Thank you very much!
